Shopping/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

from Shopping import views, settings

urlpatterns = [
    path('', views.index, name = 'index'),
    path('carrinho/', include('carrinho.urls')),
    path('sobre', views.sobre, name='sobre'),
    path('lazer', views.lazer, name='lazer'),
    path('contato', views.contato, name='contato'),
    path('loja/', include('loja.urls')),
    path('cinema/', include('filme.urls')),
    #path('pedido/', include('pedido.urls')),

    path('teatro/', include('teatro.urls')),

    path('admin/', admin.site.urls),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carrinho/urls.py
from django.urls import path

from carrinho import views

app_name = 'carrinho'

urlpatterns =[
   path('lista_produtos/', views.lista_produtos, name='lista_produtos'),
   path('cadastra_produto/', views.cadastra_produto, name='cadastra_produto'),
   path('atualiza_carrinho/', views.atualiza_carrinho, name='atualiza_carrinho'),
]

loja/urls.py
from django.urls import path

from loja import views

app_name = 'loja'

urlpatterns = [
    path('lista_loja/', views.lista_loja, name='lista_loja'),
    path('cadastra_loja/', views.cadastra_loja, name='cadastra_loja'),
    path('exibe_loja/<int:id>', views.exibe_loja, name='exibe_loja'),
    path('edita_loja/<int:id>', views.edita_loja, name='edita_loja'),
    path('remove_loja/', views.remove_loja, name='remove_loja')

]

carrinho/models.py
from django.db import models

from categoria.models import Categoria


class Carrinho(models.Model):
    categoria = models.ForeignKey(Categoria, related_name='lojas', on_delete=models.DO_NOTHING)
    nome = models.CharField(max_length=100, db_index=True, unique=True)
    models.SlugField(max_length=100)
    quantidade = models.IntegerField()
    preco = models.DecimalField(max_digits =10, decimal_places = 2)

    class Meta:
        db_table = 'carrinho'

    def __str__(self):
        return self.nome

carrinho/forms.py
from django import forms
from carrinho.models import Carrinho
from categoria.models import Categoria



class CarrinhoForm(forms.ModelForm):
    class Meta:
        model = Carrinho
        fields = ('nome', 'categoria', 'quantidade', 'preco')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['nome'].error_messages = {'required': 'Campo obrigatório.', 'unique': 'Nome de produto duplicado.'}
        self.fields['nome'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['categoria'].error_messages = {'required': 'Campo obrigatório'}
        self.fields['categoria'].queryset = Categoria.objects.all().order_by('nome')
        self.fields['categoria'].empty_label = 'Selecione a Categoria do Produto'
        self.fields['categoria'].widget.attrs.update({'class': 'form-control form-control-sm'})


        self.fields['quantidade'].error_messages = {'required': 'Campo obrigatório', }
        self.fields['quantidade'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['preco'].error_messages = {'required': 'Campo obrigatório'}
        self.fields['preco'].widget.attrs.update({'class': 'btn btn-outline-secondary btn-sm'})



class QuantidadeForm(forms.Form):

    produto_id = forms.CharField(widget=forms.HiddenInput())

    quantidade = forms.IntegerField(
        min_value=0,
        max_value=99,
        widget=forms.TextInput(attrs={'class': 'form-control-sm quantidade ',
                                      'style': 'text-align: center;  width: 70px;',
                                      'onkeypress': 'return (event.charCode>=48 && event.charCode <=57'
                                      }),
        required=True
    )

carrinho/views.py
import locale
from decimal import Decimal

from django.contrib import messages
from django.core import serializers
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.signing import Signer
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.defaultfilters import slugify
from carrinho.carrinho import Carrinho_Function
from carrinho.forms import CarrinhoForm, QuantidadeForm
from carrinho.models import Carrinho
from categoria.models import Categoria


def lista_produtos(request, slug_da_categoria=None):
    lista_de_produtos = Carrinho.objects.all().order_by('nome')
    if slug_da_categoria:
        categoria = get_object_or_404(Categoria, slug=slug_da_categoria)
        lista_de_produtos = lista_de_produtos.filter(categoria=categoria).order_by('nome')

    paginator = Paginator(lista_de_produtos, 12)
    pagina = request.GET.get('pagina')
    try:
        produtos = paginator.page(pagina)
    except PageNotAnInteger:
        produtos = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        produtos = paginator.page(paginator.num_pages)

    carrinho = Carrinho_Function(request)
    carrinho_form = CarrinhoForm()

    lista_de_forms = []
    for produto in produtos:
        qtd = produto.quantidade
        lista_de_forms.append(QuantidadeForm(initial={'quantidade': qtd, 'produto_id': produto.id}))

    preco_total = carrinho.get_preco_carrinho()
    if request.is_ajax():
        return render(request, 'carrinho/pagina_de_produtos.html', {'listas': zip(produtos, lista_de_forms), 'preco_total': preco_total, 'form': carrinho_form})

    carrinho_form = CarrinhoForm()
    return render(request, 'carrinho/lista_produtos.html', {'listas': zip(produtos, lista_de_forms), 'preco_total': preco_total, 'form': carrinho_form})



def cadastra_produto(request):

    if request.POST:
        carrinho_form = CarrinhoForm(request.POST)

        if carrinho_form.is_valid():
            carrinho = carrinho_form.save()
            carrinho2 = Carrinho_Function(request)
            carrinho2.atualiza(carrinho.id, carrinho.quantidade)
            messages.add_message(request, messages.INFO, 'Produto cadastrado com sucesso')
            carrinho.categoria = carrinho.categoria

            ser_instance = serializers.serialize('json', [ carrinho, ])

            return JsonResponse({"instance": ser_instance}, status=200)
        else:
            return JsonResponse({"error": carrinho_form.errors}, status=400)
    else:
        JsonResponse({"error": ""}, status=400)


def atualiza_carrinho(request):
    form = QuantidadeForm(request.POST)
    print(request.POST)
    if form.is_valid():
        produto_id = form.cleaned_data['produto_id']
        quantidade = form.cleaned_data['quantidade']
        produto = get_object_or_404(Carrinho, pk=produto_id)
        produto.quantidade = quantidade
        carrinho2 = Carrinho_Function(request)
        if quantidade == 0:
            produto.delete()
            carrinho2.remover(produto_id)
            messages.add_message(request, messages.INFO, 'Loja removido com sucesso.')
        else:
            carrinho2.atualiza(produto_id, quantidade)
            produto.save()
            request.session['carrinho_id'] = produto_id

        preco_total = carrinho2.get_preco_carrinho()


        return JsonResponse({'quantidade': quantidade, 'preco_total': preco_total })
    else:
        raise ValueError('Ocorreu um erro inesperado ao adicionar um produto ao carrinho.')

carrinho/templates/carrinho/cadastra_produto.html
{% load static %}

<section>
    <form action="/create_post/" method="POST" id="post-form"
             enctype="multipart/form-data" novalidate>
          <div class="row mb-xl-3">
             <div class="col-xl-6">
                <div class="row">
                   <label for="id_nome" class="col-xl-2 font-weight-bold">Nome</label>
                   <div class="col-xl-10">
                      {{ form.nome }}
                      {% if form.nome.errors %}
                         <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                            {% for error in form.nome.errors %}
                               <small>{{ error }}</small>
                            {% endfor %}
                         </div>
                      {% endif %}
                   </div>
                </div>
             </div>
          <div class="col-xl-6">
                <div class="row">
                   <label for="id_preco" class="col-xl-3 font-weight-bold">Preco</label>
                   <div class="col-xl-9">
                      {{ form.preco }}
                      {% if form.preco.errors %}
                         <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                            {% for error in form.preco.errors %}
                               <small>{{ error }}</small>
                            {% endfor %}
                         </div>
                      {% endif %}
                   </div>
                </div>
             </div>
          </div>

          <div class="row mb-xl-3">
             <div class="col-xl-6">
                <div class="row">
                   <label for="id_categoria" class="col-xl-2 font-weight-bold">Categoria</label>
                   <div class="col-xl-10">
                      {{ form.categoria }}
                      {% if form.categoria.errors %}
                         <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                            {% for error in form.categoria.errors %}
                               <small>{{ error }}</small>
                            {% endfor %}
                         </div>
                      {% endif %}
                   </div>
                </div>

             </div>
             <div class="col-xl-6">
                <div class="row">
                   <label for="id_quantidade" class="col-xl-3 font-weight-bold">Quantidade</label>
                   <div class="col-xl-9">
                      {{ form.quantidade }}
                      {% if form.quantidade.errors %}
                         <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                            {% for error in form.quantidade.errors %}
                               <small>{{ error }}</small>
                            {% endfor %}
                         </div>
                      {% endif %}
                   </div>
                </div>
             </div>
          </div>




          <div class="row mb-5">
             <div class="col-xl-6">
                <div class="row">
                   <div class="col-xl-10 offset-xl-2">
                      {% csrf_token %}
                      <button id="botao" type="submit" class="btn btn-primary">
                            <img src="{% static 'images/skin/database_add.png' %}"> Cadastrar
                      </button>
                   </div>
                </div>
             </div>
          </div>

       </form>
</section>

carrinho/templates/carrinho/lista_produtos.html
{% extends "base.html" %}

{% load static %}

{% block titulo %}
    Venda de Produtos
{% endblock %}




{% block corpo %}
    <br>
    <div id="form">
        <form action="{% url 'carrinho:cadastra_produto' %}" method="POST" id="forms"
             enctype="multipart/form-data" novalidate>
          <div class="row mb-xl-3">
             <div class="col-xl-6">
                <div class="row">
                   <label for="id_nome" class="col-xl-2 font-weight-bold">Nome</label>
                   <div class="col-xl-10">
                      {{ form.nome }}
                      {% if form.nome.errors %}
                         <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                            {% for error in form.nome.errors %}
                               <small>{{ error }}</small>
                            {% endfor %}
                         </div>
                      {% endif %}
                   </div>
                </div>
             </div>
          <div class="col-xl-6">
                <div class="row">
                   <label for="id_preco" class="col-xl-3 font-weight-bold">Preco</label>
                   <div class="col-xl-9">
                      {{ form.preco }}
                      {% if form.preco.errors %}
                         <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                            {% for error in form.preco.errors %}
                               <small>{{ error }}</small>
                            {% endfor %}
                         </div>
                      {% endif %}
                   </div>
                </div>
             </div>
          </div>

          <div class="row mb-xl-3">
             <div class="col-xl-6">
                <div class="row">
                   <label for="id_categoria" class="col-xl-2 font-weight-bold">Categoria</label>
                   <div class="col-xl-10">
                      {{ form.categoria }}
                      {% if form.categoria.errors %}
                         <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                            {% for error in form.categoria.errors %}
                               <small>{{ error }}</small>
                            {% endfor %}
                         </div>
                      {% endif %}
                   </div>
                </div>

             </div>
             <div class="col-xl-6">
                <div class="row">
                   <label for="id_quantidade" class="col-xl-3 font-weight-bold">Quantidade</label>
                   <div class="col-xl-9">
                      {{ form.quantidade }}
                      {% if form.quantidade.errors %}
                         <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                            {% for error in form.quantidade.errors %}
                               <small>{{ error }}</small>
                            {% endfor %}
                         </div>
                      {% endif %}
                   </div>
                </div>
             </div>
          </div>




          <div class="row mb-5">
             <div class="col-xl-6">
                <div class="row">
                   <div class="col-xl-10 offset-xl-2">
                      {% csrf_token %}
                      <button id="botao" type="submit" class="btn btn-primary">
                            <img src="{% static 'images/skin/database_add.png' %}"> Cadastrar
                      </button>
                   </div>
                </div>
             </div>
          </div>

       </form>
    </div>


        <table id = "tabela" class="table table-striped table-sm  justify-content-center">
        <thead>
                <tr>
                    <th class = "text-center">Nome</th>
                    <th class = "text-center">Categoria</th>
                    <th class = "text-center">Preço</th>
                    <th class = "text-center">Quantidade</th>

                </tr>
        </thead>
            <tbody id="lista-produtos">
                     {% include 'carrinho/pagina_de_produtos.html' %}

            <tr>
                  <td colspan="3">
                     <strong style="margin-left: 10px">Valor Total do Carrinho em Reais</strong>
                  </td>
                  <td class="text-right pr-5">
                      <strong id="valor-do-carrinho">{{preco_total}}</strong>
                  </td>
                  <td></td>
            </tr>
            </tbody>
            </table>

    <!-- </div> -->

{% endblock %}

{% block domready %}


     $("#forms").submit(function (e) {
        e.preventDefault();

        var serializedData = $(this).serialize();

        $.ajax({
            type: 'POST',
            url: "{% url 'carrinho:cadastra_produto' %}",
            data: serializedData,
            success: function (response) {

                var instance = JSON.parse(response["instance"]);
                console.log(instance)

                var fields = instance[0]["fields"];
                var id = instance[0]["pk"];

                console.log(fields, id)

                $("#lista-produtos").prepend(
                    `<tr>
                <td class ="text-center">
                    ${fields["nome"]||""}
                </td>
                <td class ="text-center">
                    ${fields["categoria"]||""}
                </td>
                <td class ="text-center">
                     ${fields["preco"]||""}

                </td>
                <td class="text-center">
                        <form class="mx-auto" style="width: 60px" action="/carrinho/atualiza_carrinho/" method="post" novalidate="">
                            {% csrf_token %}
                                <input type="hidden" name="produto_id" value='${id}' id="id_produto_id">
                                <input type="text" name="quantidade" value='${fields["quantidade"]||""}' class="form-control-sm quantidade " style="text-align: center;  width: 70px;" onkeypress="return (event.charCode>=48 &amp;&amp; event.charCode <=57" required="" id="id_quantidade">
                            <button style="margin-top: 0px; margin-bottom: 0px;
                                          padding-top: 3px; padding-bottom: 3px;
                                          width: 40px" type="button" class="btn btn-sm btn-danger remover" tabindex="-1">
                              <img src="/static/images/skin/remove.png">
                       </button>
                        </form>
                </td>
                </tr>`
                )
                 console.log(fields.quantidade * fields.preco)
                 $("#valor-do-carrinho").text(parseFloat(parseFloat($("#valor-do-carrinho").text().replace(',', '.')) + (fields.quantidade * fields.preco)).toFixed(2))
                },
            error: function (response) {
                alert(response["responseJSON"]["error"]);
            }
        })
    })



   var pagina = 1;
   var empty_page = false;
   var block_request = false;

   if ($(window).width() >= 1200)
      percentual = 22/100
   else if ($(window).width() >= 992)
      percentual = 30/100
   else if ($(window).width() >= 768)
      percentual = 40/100
   else if ($(window).width() >= 576)
      percentual = 60/100
   else
      percentual = 70/100

   $(window).scroll(function() {
      if  (($(document).height() - $(window).height() - $(window).scrollTop() < percentual * $(window).height())
           && empty_page == false && block_request == false) {
		   block_request = true;
		   pagina += 1;
		   $.get('?pagina=' + pagina, function(resposta) {
		      if(resposta == '') {
		         empty_page = true;
		      }
		      else {
               block_request = false;
               $('#lista-produtos').append(resposta);
    	      }
         });
    	}
   });


       $("#tabela").on("blur", "input.quantidade", function() {
      let valor = $(this).val()
      if (valor < 1 || valor > 99) {
         $(this).focus()
         return
      }

      let form = $(this).parent()
      let tr = form.parent().parent()
      let url = form.attr("action")
      let formData = form.serializeArray()
      $.post(url, formData, function(resposta) {
         tr.find(".preco-total").text(resposta.preco_total)
    $("#valor-do-carrinho").text(resposta.preco_total)

      })
   })

   $("#tabela").on("click", ".remover", function() {
      let form = $(this).parent()
      form.append('<input type="hidden" name="quantidade" value="0">')
      let tr = form.parent().parent()
      let url = form.attr('action')
      let formData = form.serializeArray()
      $.post(url, formData, function(resposta) {

         tr.fadeTo('slow', 0.3, function() {
            $(this).remove()
             tr.find(".preco-total").text(resposta.preco_total)
             $("#valor-do-carrinho").text(resposta.preco_total)
         })
      })
   })

{% endblock %}

carrinho/templates/carrinho/pagina_de_produtos.html
{% load static %}


        {% for produto, form in listas %}
            <tr>
                <td class ="text-center">
                    {{produto.nome }}
                </td>
                <td class ="text-center">
                    {{produto.categoria}}
                </td>
                <td class ="text-center">
                     {{produto.preco}}

                </td>
                    <td class ="text-center">
                        <form class="mx-auto" style="width: 60px" action="{% url 'carrinho:atualiza_carrinho' %}" method="post" novalidate>
                            {% csrf_token %}
                                {{ form.produto_id }}
                                {{form.quantidade }}
                            <button style="margin-top: 0px; margin-bottom: 0px;
                                          padding-top: 3px; padding-bottom: 3px;
                                          width: 40px"
                                type="button"
                                class="btn btn-sm btn-danger remover"
                                   tabindex="-1">
                              <img src="{% static 'images/skin/remove.png' %}">
                       </button>
                        </form>


                </td>
                </tr>
   {% endfor %}