Shopping/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

from Shopping import views, settings

urlpatterns = [
    path('', views.index, name = 'index'),
    path('carrinho/', include('carrinho.urls')),
    path('sobre', views.sobre, name='sobre'),
    path('lazer', views.lazer, name='lazer'),
    path('contato', views.contato, name='contato'),
    path('loja/', include('loja.urls')),
    path('cinema/', include('filme.urls')),
    #path('pedido/', include('pedido.urls')),

    path('teatro/', include('teatro.urls')),

    path('admin/', admin.site.urls),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loja/urls.py
from django.urls import path

from loja import views

app_name = 'loja'

urlpatterns = [
    path('lista_loja/', views.lista_loja, name='lista_loja'),
    path('cadastra_loja/', views.cadastra_loja, name='cadastra_loja'),
    path('exibe_loja/<int:id>', views.exibe_loja, name='exibe_loja'),
    path('edita_loja/<int:id>', views.edita_loja, name='edita_loja'),
    path('remove_loja/', views.remove_loja, name='remove_loja')

]

loja/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

from categoria.models import Categoria


class Loja(models.Model):
    categoria = models.ForeignKey(Categoria, related_name='produtos', on_delete=models.DO_NOTHING)
    nome = models.CharField(max_length=100, db_index=True, unique = True)
    slug = models.SlugField(max_length=100)
    imagem = models.ImageField(upload_to='images/')
    descricao = models.CharField(max_length=300)
    cnpj = models.CharField(max_length=14)
    data_cadastro = models.DateField()


    class Meta:
        db_table='loja'


    def __str__(self):
        return self.nome

loja/forms.py
from django import forms
from django.core import serializers
from django.core.exceptions import ValidationError

from itertools import cycle

from Shopping import settings
from categoria.models import Categoria
from loja.models import Loja


class PesquisaLojaForm(forms.Form):
    nome = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '100'}),
        required=False
    )




class LojaForm(forms.ModelForm):
    class Meta:
        model = Loja
        fields = ('nome', 'categoria', 'cnpj', 'data_cadastro', 'descricao', 'imagem')

    def clean_cnpj(self):
        cnpj = self.cleaned_data['cnpj']
        if len(cnpj) != 14:
            raise ValidationError("CNPJ Invalido. Verifique e tente novamente!")

        if cnpj in (c * 14 for c in "1234567890"):
            raise ValidationError("CNPJ Invalido. Verifique e tente novamente!")

        cnpj_r = cnpj[::-1]
        for i in range(2, 0, -1):
            cnpj_enum = zip(cycle(range(2, 10)), cnpj_r[i:])
            dv = sum(map(lambda x: int(x[1]) * x[0], cnpj_enum)) * 10 % 11
            if cnpj_r[i - 1:i] != str(dv % 10):
                raise ValidationError("CNPJ Invalido. Verifique e tente novamente!")

        return cnpj

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['nome'].error_messages = {'required': 'Campo obrigatório.', 'unique': 'Nome de produto duplicado.'}
        self.fields['nome'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['descricao'].error_messages = {'required': 'Campo obrigatório'}
        self.fields['descricao'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['categoria'].error_messages = {'required': 'Campo obrigatório'}
        self.fields['categoria'].queryset = Categoria.objects.all().order_by('nome')
        self.fields['categoria'].empty_label = 'Selecione a Categoria da Loja'
        self.fields['categoria'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['data_cadastro'].error_messages = {'required': 'Campo obrigatório', 'invalid': 'Data inválida'}
        self.fields['data_cadastro'].input_formats = settings.DATE_INPUT_FORMATS
        self.fields['data_cadastro'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['cnpj'].error_messages = {'required': 'Campo obrigatório', }
        self.fields['cnpj'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['imagem'].error_messages = {'required': 'Campo obrigatório', 'invalid_image': 'Imagem Inválida'}
        self.fields['imagem'].widget.attrs.update({'class': 'btn btn-outline-secondary btn-sm'})

loja/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.template.defaultfilters import slugify

from loja.forms import PesquisaLojaForm, LojaForm
from loja.models import Loja


def lista_loja(request):
    form = PesquisaLojaForm(request.GET)
    if form.is_valid():
        nome = form.cleaned_data['nome']
        lista_de_lojas = Loja.objects.filter(nome__icontains=nome).order_by('nome')
        paginator = Paginator(lista_de_lojas, 3)
        pagina = request.GET.get('pagina')
        page_obj = paginator.get_page(pagina)
        return render(request, 'loja/pesquisa_loja.html', {'lojas': page_obj,
                                                           'form': form,
                                                           'nome': nome})

    else:
        raise ValueError("Ocorreu um erro inesperado ao tentar recuperar a loja")


def cadastra_loja(request):

    if request.POST:
        loja_id = request.session.get('loja_id')
        if loja_id:
            loja = get_object_or_404(Loja, pk= loja_id)
            loja_form = LojaForm(request.POST, request.FILES, instance=loja)

        else:
            loja_form = LojaForm(request.POST, request.FILES)

        if loja_form.is_valid():
            loja = loja_form.save(commit=False)
            loja.slug = slugify(loja.nome)
            loja.save()

            if loja_id:
                messages.add_message(request, messages.INFO, 'Loja alterada com sucesso')
                del request.session['loja_id']
            else:
                messages.add_message(request, messages.INFO, 'Loja cadastrada com sucesso')

            return redirect('loja:exibe_loja', id = loja.id)

    else:
        try:
            del request.session['loja_id']
        except KeyError:
            pass
        loja_form = LojaForm()


    return render(request, 'loja/cadastra_loja.html', {'form': loja_form})
def exibe_loja(request, id):
    loja = get_object_or_404(Loja, pk = id)
    request.session['loja_id_del'] = id
    return render(request, 'loja/exibe_loja.html', {'loja': loja})


def edita_loja(request, id):
    loja = get_object_or_404(Loja, pk=id)
    loja_form = LojaForm(instance=loja)
    request.session['loja_id'] = id
    return render(request, 'loja/cadastra_loja.html', {'form': loja_form})


def remove_loja(request):
    loja_id = request.session.get('loja_id_del')
    loja = get_object_or_404(Loja, id=loja_id)
    loja.imagem.delete()
    loja.delete()
    del request.session['loja_id_del']
    messages.add_message(request, messages.INFO, 'Loja removido com sucesso.')
    return render(request, 'loja/exibe_loja.html', {'loja': loja})

loja/templates/loja/cadastra_loja.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}Cadastro de Lojas{% endblock %}
{% block corpo %}

    <div class="mb-4">
        <h5>Cadastro de Loja</h5>
        <hr class="mt-0">
    </div>


<form action="{% url 'loja:cadastra_loja' %}" method="POST" class="pb-4"
         enctype="multipart/form-data" novalidate>
      <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_nome" class="col-xl-2 font-weight-bold">Nome</label>
               <div class="col-xl-10">
                  {{ form.nome }}
                  {% if form.nome.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.nome.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
         <div class="col-xl-6">
            <div class="row">
               <label for="id_descricao" class="col-xl-3 font-weight-bold">Descrição</label>
               <div class="col-xl-9">
                  {{ form.descricao }}
                  {% if form.descricao.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.descricao.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
      </div>

      <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_categoria" class="col-xl-2 font-weight-bold">Categoria</label>
               <div class="col-xl-10">
                  {{ form.categoria }}
                  {% if form.categoria.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.categoria.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
         <div class="col-xl-6">
            <div class="row">
               <label for="id_data_cadastro" class="col-xl-3 font-weight-bold">Data Cadastro</label>
               <div class="col-xl-9">
                  {{ form.data_cadastro }}
                  {% if form.data_cadastro.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.data_cadastro.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
      </div>

      <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_cnpj" class="col-xl-2 font-weight-bold">CNPJ</label>
               <div class="col-xl-10">
                  {{ form.cnpj }}
                  {% if form.cnpj.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.cnpj.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>

         <div class="col-xl-6">
            <div class="row">
               <label for="id_imagem" class="col-xl-3 font-weight-bold">Imagem</label>
               <div class="col-xl-9">
                  {{ form.imagem }}
                  {% if form.imagem.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.imagem.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>

      <div class="row mb-5">
         <div class="col-xl-6">
            <div class="row">
               <div class="col-xl-10 offset-xl-2">
                  {% csrf_token %}
                  <button id="botao" type="submit" class="btn btn-primary">
                     {% if 'loja_id' in request.session %}
                        <img src="{% static 'images/skin/database_edit.png' %}"> Alterar
                     {% else %}
                        <img src="{% static 'images/skin/database_add.png' %}"> Cadastrar
                     {% endif %}
                  </button>
               </div>
            </div>
         </div>
      </div>

   </form>



{% endblock %}


{% block domready %}

    $('#id_data_cadastro').datepicker({
       changeMonth: true,
       changeYear: true,
       yearRange: "-3:+0",
       dateFormat: 'dd/mm/yy',
       dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
       dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
       dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
       monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
       monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
       nextText: 'Próximo',
       prevText: 'Anterior',
       showOn: 'focus',
   })

   $('#id_data_cadastro').mask('00/00/0000')
{% endblock %}

loja/templates/loja/exibe_loja.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
   Exibe Loja
{% endblock %}

{% block corpo %}
   <div class='mb-4'>
      <h5>Informações sobre a loja</h5>
      <hr class='mt-0'>
   </div>

      {% if messages %}
         <div class="mb-3">
            {% for message in messages %}
               <ul class="list-group rounded">
                  <li style="padding-top: 7px; padding-bottom: 7px"
                      class="list-group-item list-group-item-info">
                     {{ message }}
                  </li>
               </ul>
            {% endfor %}
         </div>
      {% endif %}

      <div class="row mb-3">
         <div class="col-lg-3 col-md-4">
            {% if loja.imagem %}
               <img class="mr-3" style="width: 210px"
                    src="{{loja.imagem.url}}" alt="{{ loja.nome }}">
            {% else %}
               <div class="text-md-center mb-md-0 mb-2">
                  Imagem não disponível
               </div>
            {% endif %}
         </div>
         <div class="col-lg-9 col-md-8">
            <div class="row">
               <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Categoria</div>
               <div class="col-xl-10 col-lg-9 col-8">{{ loja.categoria }}</div>
               <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Nome</div>
               <div class="col-xl-10 col-lg-9 col-8">{{ loja.nome }} </div>
                <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Descrição</div>
               <div class="col-xl-10 col-lg-9 col-8">{{ loja.descricao }}</div>
                <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Cnpj</div>
               <div class="col-xl-10 col-lg-9 col-8">{{ loja.cnpj }}</div>
               <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Data de Inauguração</div>
               <div class="col-xl-10 col-lg-9 col-8">{{ loja.data_cadastro | date:'d/m/Y' }}</div>
            </div>
         </div>
      </div>

      {% if loja.id %}
         <div class="form-group row">
            <div class="col-12">
               <div class="form-inline">
                  <a href="{% url 'loja:edita_loja' loja.id %}" class="btn btn-primary mr-3">
                     <img src="{% static 'images/skin/database_edit.png' %}" /> Editar
                  </a>

                  <form action="{% url 'loja:remove_loja'%}" method="POST">
                     {% csrf_token %}
                     <button type="submit" class="btn btn-danger">
                        <img src="{% static 'images/skin/database_delete.png' %}"> Remover
                     </button>
                  </form>
               </div>
            </div>
         </div>
      {% endif %}
{% endblock %}

loja/templates/loja/pesquisa_loja.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}Pesquisa de Lojas{% endblock %}
{% block corpo %}

    <div class="mb-4">
        <h5>Pesquisa de Produtos</h5>
        <hr class="mt-0">
    </div>

    <form action="" method="GET" class="mb-4">
        <div class="form-group row" style="margin-bottom: 10px">
            <label for="id_nome" class="col-lg-2 col-form-label font-weigth-bold">Nome</label>
            <div class="col-lg-10">
                {{ form.nome }}
            </div>
        </div>
        <div class="form-group row">
            <div class="col-lg-10 offset-lg-2">
                <button type="submit" class="btn btn-primary">
                    <div class="d-flex align-items-center">
                        <img src="{% static 'images/skin/binoculo.png' %}" class="mr-2">Pesquisar
                    </div>
                </button>
            </div>
        </div>

    </form>

    <div>
        {% if lojas %}
            </div>
    <h5 class="mb-5"> Lista de Lojas</h5>
    <table style="width: 100%" class="table table-striped table-sm table-bordered table-responsive mb-4">
        <thead>
            <tr>
                <th class = "text-center">Imagem</th>
                <th class = "text-center">Categoria</th>
                <th class = "text-center">Nome</th>
                <th class = "text-center">CNPJ</th>

                <th class = "text-center">Descrição</th>
                <th class = "text-center">Data de Inauguração</th>
            </tr>
        </thead>
        <tbody>
            {% for loja in lojas %}
                <tr>
                    <td style = "width: 15%" class ="text-center align-middle">
                        <a href="{% url 'loja:exibe_loja' loja.id %}">
                            <img style="width: 80px" src ="{{ loja.imagem.url}}" alt="{{ loja.nome }}">

                        </a>
                    </td>
                <td style = "width: 15%" class ="text-center align-middle">
                    {{loja.categoria}}
                </td>
                <td style = "width: 15%" class ="text-center align-middle">
                    <a href="{% url 'loja:exibe_loja' loja.id %}">
                        {{loja.nome}}

                    </a>
                </td>
                    <td style = "width: 15%" class ="align-middle">
                    {{loja.cnpj}}
                </td>
                <td style = "width: 25%" class ="align-middle">
                    {{loja.descricao}}
                </td>
                <td style = "width: 15%" class ="text-center align-middle">
                    {{loja.data_cadastro | date:'d/m/Y'}}
                </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
     <div style='font-size: 14px; margin-bottom: 28px'>
      {% if lojas.has_other_pages %}
         <ul class='pagination'>
            {% if lojas.has_previous %}
               <li class='page-item'><a class='page-link' href='?pagina={{ lojas.previous_page_number }}&nome={{ nome }}'>Anterior</a></li>
            {% else %}
               <li class='page-item disabled'><a class='page-link' href='#' tabindex='-1'>Anterior</a></li>
            {% endif %}
            {% for i in lojas.paginator.page_range %}
               {% if lojas.number == i %}
                  <li class='page-item active'><a class='page-link' href='#'>{{ i }} </a></li>
               {% else %}
                  <li class='page-item'><a class='page-link' href='?pagina={{ i }}&nome={{ nome }}'>{{ i }}</a></li>
               {% endif %}
            {% endfor %}
            {% if lojas.has_next %}
               <li class='page-item'><a class='page-link' href='?pagina={{ lojas.next_page_number }}&nome={{ nome }}'>Próxima</a></li>
            {% else %}
               <li class='page-item disabled'><a class='page-link' href='#' tabindex='-1'>Próxima</a></li>
            {% endif %}
         </ul>
      {% endif %}
   </div>
        {% else%}
            <h3>Não temos nenhum filme agendado no momento</h3>
    {% endif %}



{% endblock %}