Shopping/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

from Shopping import views, settings

urlpatterns = [
    path('', views.index, name = 'index'),
    path('carrinho/', include('carrinho.urls')),
    path('sobre', views.sobre, name='sobre'),
    path('lazer', views.lazer, name='lazer'),
    path('contato', views.contato, name='contato'),
    path('loja/', include('loja.urls')),
    path('cinema/', include('filme.urls')),
    #path('pedido/', include('pedido.urls')),

    path('teatro/', include('teatro.urls')),

    path('admin/', admin.site.urls),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carrinho/urls.py
from django.urls import path

from carrinho import views

app_name = 'carrinho'

urlpatterns =[
   path('lista_produtos/', views.lista_produtos, name='lista_produtos'),
   path('cadastra_produto/', views.cadastra_produto, name='cadastra_produto'),
   path('atualiza_carrinho/', views.atualiza_carrinho, name='atualiza_carrinho'),
]

filme/urls.py
from django.urls import path

from filme import views

app_name = 'filmes'

urlpatterns = [
    path('filmes/', views.filmes, name='filmes')

]

loja/urls.py
from django.urls import path

from loja import views

app_name = 'loja'

urlpatterns = [
    path('lista_loja/', views.lista_loja, name='lista_loja'),
    path('cadastra_loja/', views.cadastra_loja, name='cadastra_loja'),
    path('exibe_loja/<int:id>', views.exibe_loja, name='exibe_loja'),
    path('edita_loja/<int:id>', views.edita_loja, name='edita_loja'),
    path('remove_loja/', views.remove_loja, name='remove_loja')

]

teatro/urls.py
from django.urls import path

from teatro import views

app_name = 'teatro'

urlpatterns = [
    path('pecas/', views.teatro, name='teatro')

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/all.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <title> {% block titulo %}ShoppingMall{% endblock %}</title>
    <style>
        {% block estilo %}
        {% endblock %}
    </style>



</head>
<body>

    <div id="container_all" class="container_all">
    {% block cabecalho %}
    <nav class="navbar navbar-light bg-light navbar-expand-md">
    <div class="container">
      <a class="navbar-brand" href="{%  url 'index' %}"><img src="{% static 'images//logo.jfif'%}" alt="Logo Shopping"
          style="width: 80px"></a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu" aria-controls="menu"
        aria-expanded="false" aria-label="Botão de navegação">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="menu">

        <div class="navbar-nav mx-auto ">
          <a class="nav-link nav-item pr-5" href="{%  url 'sobre' %}">Sobre o Shopping</a>
          <a class="nav-link nav-item pr-5"  href="{%  url 'loja:lista_loja' %}">Nossas Lojas</a>
          <a class="nav-link nav-item pr-5"  href="{%  url 'loja:cadastra_loja' %}">Cadastrar Lojas</a>
          <a class="nav-link nav-item pr-5"  href="{%  url 'carrinho:lista_produtos' %}">Trabalho 6</a>

          <a class="nav-link nav-item pr-5"  href="{%  url 'filmes:filmes' %}">Cinema</a>
          <a class="nav-link nav-item pr-5"  href="{%  url 'teatro:teatro' %}">Teatro</a>

          <!-- Em construção <a class="nav-link nav-item pr-5" href="#% url 'contato' %}">Contato <i class="fa-solid fa-phone"></i></a> -->
        </div>
      </div>


    </div>

  </nav>


    {% endblock %}

    {% block corpo %}
    {% endblock %}
    </div>

    {% block rodape %}
        <div class="footer row justify-content-md-center">
    <div class="footerpt1">

      <h4>Shopping Lorem Ipsum</h4>
      <br>
      <h7>Siga a gente nas Redes Sociais</h7>
    </div>


    <div class="footerpt1">

      <div style='font-size:15px'> Endereço</div>
      <div style='font-size:8px'> Rua do Shopping 123, bloco 48</div>
      <br>
      <div style='font-size:15px'> Para mais Informações</div>
      <div style='font-size:8px'> (55)1234-5678</div>

    </div>

    <div class="footerpt1">

      <div style='font-size:15px'> Horário de Funcionamento:
      </div>
      <div style='font-size:10px'>Lojas e Quiosques:</div>
      <div style='font-size:8px'>Segunda à Sábado, das 10h às 22h</div>
      <div style='font-size:8px'>Domingos e Feriados, das 14h às 20h</div>

      <br>
      <div style='font-size:15px'> Alimentação:</div>
      <div style='font-size:8px'> Todos os dias, das 11h às 22h</div>

    </div>
  </div>

  </div>
    {% endblock %}
</body>
  <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
  <script src="{% static 'js/jquery-ui.min.js' %}"></script>
  <script src="{% static 'js/jquery.mask.js' %}"></script>
  <script src="{% static 'js/popper.js' %}"></script>
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <script src="{% static 'js/script.js' %}"></script>

  <script>
        $(document).ready(function() {
            {% block domready %}

            {% endblock %}
        })


    </script>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
    Shopping Lore Ipsum
{% endblock %}
{% block corpo %}


  <div id="carouselShopping" class="carousel slide " data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselShopping" data-slide-to="0" class="active"></li>
      <li data-target="#carouselShopping" data-slide-to="1"></li>
      <li data-target="#carouselShopping" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="{% static 'images/banner1.png' %}" alt="Relogio">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'images/banner2.jpg' %}" alt="Imagem da Segunda Propaganda">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'images/banner3.png' %}" alt="Imagem da Terceira Propaganda">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselShopping" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">voltar</span>
    </a>
    <a class="carousel-control-next" href="#carouselShopping" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">avançar</span>
    </a>
  </div>

  <div class="p-3 mb-2 bg-light text-dark text-center">
    <h1>Conheça alguma de nossas lojas</h1>
  </div>


  <div class="row justify-content-md-center">

        {% for loja in lojas %}
            <div class ="col-lg-3 d-flex align-items-stretch">
                 <div class="card mb-3 mb-3 ml-5 mr-5">
                  <image src ="{{ loja.imagem.url}}" alt="{{ loja.nome }}" title="Card com o logo e informações da loja do {{ loja.nome }}"></image>
                  <div class="card-body text-center">
                    <div class="text-center">
                      <h5 class="card-title">{{ loja.nome }}</h5>
                      <p class="text-secondary font-weight-bold">{{ loja.categoria }}</p>
                    </div>

                    <p class="card-text text-center">{{ loja.descricao }}</p>
                  </div>
                </div>
            </div>

        {% endfor %}


  </div>

{% endblock %}

templates/sobre.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
    Sobre o Shopping
{% endblock %}
{% block corpo %}
    <div class="sobrenos row">
    <div class="mr-5">
      <div class="mr-5">
        <div class="mr-5" style='font-size:45px'>Estamos no Rio Shopping,</div>
        <strong style='font-size:45px'>Aguardando vocês!</strong>
        <br>
        <div class="mt-1" style='font-size:15px'>Temos de tudo. Com o melhor que um shopping pode oferecer!</div>
      </div>
    </div>

    <img class="img-fluid " id="imagemsobre" src="{% static 'images/imagemsobre.png' %}" alt="Imagem do Shopping" width="600"
      height="400">
  </div>

  <div class="sobre2">
    <div style='font-size:55px'>O Shopping
    </div>
    <div class="mt-1" style='font-size:17px'>Localizado em um dos endereços mais elegantes do Rio de Janeiro, o
      Shopping<br> vai além de uma experiência de compras.

      Com aproximadamente 94 mil metros<br> de área construída e com vista para um dos principais cartões portais da
      cidade<br>, o morro do Corcovado, onde está localizado o Cristo Redentor, o espaço mescla<br> arte, gastronomia e
      moda.</div>
  </div>
  </div>
  <div class="sobre3 mt-5">
    <div style='font-size:45px'>Informações Gerais
    </div>
    <p>
      <a class="btn btn-light" data-toggle="collapse" href="#textocinema" role="button" aria-expanded="false"
        aria-controls="collapseExample">
        Cinema
      </a>
      <a class="btn btn-light" data-toggle="collapse" href="#textogaragem" role="button" aria-expanded="false"
        aria-controls="collapseExample">
        Garagem
      </a>
      <a class="btn btn-light" data-toggle="collapse" href="#textopessoa" role="button" aria-expanded="false"
        aria-controls="collapseExample">
        Inauguração e Fluxo de pessoa
      </a>
    </p>
    <div class="collapse mr-5 mb-3" id="textocinema">
      <div class="card card-body">
        Nosso cinema apresenta 20 salas do maior luxo que um cinema pode oferecer. Aqui sua experiência será
        inigualável. Não perca essa oportunidade e garanta já seu ingresso.
      </div>
    </div>
    <div class="collapse mr-5 mb-3" id="textogaragem">
      <div class="card card-body">
        Nossa garagem é altamente segura, com diversos pontos de fiscalização. Aqui você sabe que seu bem estar é nosso
        objetivo. Temos ao todo 8500 vagas. Para verificar disponibilidade baixe já nosso aplicativo na UFF Store.
      </div>
    </div>
    <div class="collapse mr-5 mb-3" id="textopessoa">
      <div class="card card-body">
        Desde 2001 no mercado, nosso shopping tem um fluxo estimado de 5 milhões de pessoas por mês.
      </div>
    </div>
  </div>
  </div>
{% endblock %}